# -*- coding: utf-8 -*-
"""python_sql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9Q_BQJWVONGlyKFiDIMyZstP8tn_EGO

# Banco de Dados

* Componentes
  * Base de dados
  * Sistema Gerenciador de Banco de Dados (SGBD)
  * Linguagem de Manipulação
  *  Structered Query Language (SQL)
  * Programas adicionais

* Arquitetura
  * Cliente-Servidor

## Modelo Relacional
  
| nome | tipo | nivel | capturado em|
|---- |----|-----|----|
|Pikachu| Elétrico| 5| 08 jun 2021|
|Bulbassauro| Grama| 10| 10 fev 1990|
|Squirtle| Água| 12| 23 out 2015|

Tabela ou Relação

Linhas, Intâncias, Entradas, Registros, Tupla

Colunas, atributos, características

## Implementação em SQL

* dialetos: MySQL, PostreSQL, MariaDB, Oracle etc

* MySQL online: https://paiza.io/en/projects/new?language=mysql
* PostgreSQL as a Service: https://www.elephantsql.com/
* Sqlite e PostgreSQL: https://sqliteonline.com/

#### Criando um banco de dados dentro do SGDB
* MySQL
      CREATE DATABASE [IF NOT EXISTS] db_name
*PostgreSQL
      CREATE DATABASE name
*SQLite
      # Não tem (nesse formato)

### Linguagem de Descrição de Dados (DDL)

#### CREATE (Criar)
      CREATE [TEMPORARY] TABLE [IF NOT EXISTS] tbl_name
      [column_name column_type column_constraint, ...]
      [table_constraints, ...]

[MySQL types](https://dev.mysql.com/doc/refman/8.0/en/data-types.html)
\- [PostrgreSQL types](https://www.postgresql.org/docs/9.5/datatype.html)
\- [SQLite types](https://www.sqlite.org/datatype3.html)

* Most used Constraints:

#### ALTER (alterar)
      ALTER TABLE tbl_name [alter_option, ...]

#### DROP (descartar)
      DROP TABLE [ IF EXISTS ] tbl_name [, ...]

### Linguagem de Manipulação de Dados (DML)

#### INSERT (inserir)

      INSERT  INTO tbl_name[(col_name [, col_name] ...)]
      VALUES (value_list) [, (value_list)] ...```


#### UPDATE (atualizar)
      UPDATE table_reference
      SET assignment_list
      [WHERE where_condition]

#### DELETE (deletar)
      DELETE FROM tbl_name [WHERE where_condition]

### Linguagem de Consulta de Dados (DQL)

#### SELECT (SELECIONAR)

      SELECT [ALL | ISTINCT | DISTINCTROW ]
      select_expr [, select_expr] ...
      [FROM table_references
      [WHERE where_condition]
      [GROUP BY {col_name | expr | position}, ...]
      [HAVING where_condition]
      [ORDER BY {col_name | expr | position} [ASC | DESC], ...]
      [LIMIT {[offset,] row_count | row_count OFFSET offset}]

#### JOINS

### Linguagem de Transação de Dados (DTL)
### Linguagem de Controle de Dados (DCL)

# Integração com Python
"""

import sqlite3

con = sqlite3.connect("pokemon.bd")

con.execute("""
CREATE TABLE Treinadores(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome VARCHAR(30) NOT NULL UNIQUE,
  cidade VARCHAR(30),
  insignias INTEGER NOT NULL DEFAULT 0
);
            """)

con.execute("""
CREATE TABLE IF NOT EXISTS Pokemon(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome VARCHAR(25) NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  nivel INTEGER NOT NULL default 1,
  capturado_em DATE default CURRENT_DATE,
  id_treinador INTEGER NOT NULL REFERENCES Treinadores(id)
);
""")

treinadores = [
    {
        'nome': 'Ash',
        'cidade': 'Pallet'
    },
    {
        'nome': 'Feulo',
        'cidade': 'SP'
    },
    {
        'nome': 'Gary',
        'cidade': 'Pallet'
    }
  ]

for treinador in treinadores:
  con.execute(f"INSERT INTO treinadores(nome, cidade) VALUES ('{treinador['nome']}', '{treinador['cidade']}')")
con.commit()

rs = con.execute("SELECT * FROM Treinadores")

rs

resultados = rs.fetchall()    # list[tuple[int, str, str, int]]

resultados

for treinador in rs.fetchall():
  if treinador[1] == 'Feulo':
    print(f"Campeão!! {treinador[1]}")
  else:
    print(f"Perdedor: {treinador[1]}")

con.execute("""INSERT INTO Pokemon (nome, tipo, nivel, capturado_em, id_treinador)
VALUES
('Bulbasaur', 'Grama', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Charmander', 'Fogo', 6, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Squirtle', 'Água', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Pikachu', 'Elétrico', 7, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Jigglypuff', 'Fada', 4, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Psyduck', 'Água', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Geodude', 'Pedra', 6, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Snorlax', 'Normal', 8, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Magikarp', 'Água', 3, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Gengar', 'Fantasma', 9, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
-- Insira mais Pokémons aqui usando a mesma estrutura, ajustando os valores de nome, tipo, nível, capturado_em e id_treinador conforme necessário.
('Zubat', 'Venenoso', 4, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Golbat', 'Venenoso', 7, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Oddish', 'Grama', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Gloom', 'Grama', 8, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Vileplume', 'Grama', 10, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Paras', 'Inseto', 3, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Parasect', 'Inseto', 6, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Venonat', 'Inseto', 4, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Venomoth', 'Inseto', 7, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Diglett', 'Terra', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Dugtrio', 'Terra', 8, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Meowth', 'Normal', 4, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Persian', 'Normal', 7, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Psyduck', 'Água', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Golduck', 'Água', 8, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Mankey', 'Lutador', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Primeape', 'Lutador', 8, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Growlithe', 'Fogo', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Arcanine', 'Fogo', 8, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Poliwag', 'Água', 4, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Poliwhirl', 'Água', 6, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Poliwrath', 'Água', 9, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Abra', 'Psíquico', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Kadabra', 'Psíquico', 7, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Alakazam', 'Psíquico', 10, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Machop', 'Lutador', 6, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Machoke', 'Lutador', 8, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Machamp', 'Lutador', 10, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Bellsprout', 'Grama', 4, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Weepinbell', 'Grama', 6, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Victreebel', 'Grama', 9, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Tentacool', 'Água', 4, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Tentacruel', 'Água', 7, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1)),
('Geodude', 'Pedra', 5, CURRENT_DATE, (SELECT id FROM Treinadores ORDER BY RANDOM() LIMIT 1));""")
con.commit()

rs = con.execute("SELECT * FROM pokemon WHERE nivel > 5")

rs.fetchmany(1)

for result in rs:
  print(f"Capturei o Pokemon: {result[0]}!!")

rs.fetchone()

rs.fetchone()

rs.fetchall()

rs.fetchmany(2)

"""## Psycopg2"""

!pip install psycopg2

import psycopg2

#protocolo://usuario:senha@host:[porta]/banco
url = "postgresql://bdnwdsqa:Fcuac9fB3VdD5urWL2Hf43nrjDUhPAz4@isabelle.db.elephantsql.com/bdnwdsqa"
con = psycopg2.connect(url)
cur = con.cursor()

cur.execute("""CREATE TABLE Treinadores (
   id SERIAL PRIMARY KEY,
   nome VARCHAR(20) NOT NULL,
   cidade VARCHAR(20)
 );""")

cur.execute("""INSERT INTO Treinadores(nome, cidade) VALUES
('Ash', 'Pallet'),
('Feulo', 'SP');
""")

con.commit()

cur.execute("SELECT * FROM Treinadores;")
rs = cur.fetchall()

rs

"""# SQLAlchemy"""

! pip freeze | grep SQLAlchemy

! pip install -U sqlalchemy

from sqlalchemy import create_engine
from sqlalchemy.sql import text

# Cria a engine para o banco de dados
eng_postgres = create_engine("postgresql://gzxgfccf:gBkismk7ebdandSt_b3ry5d5Q015yTrK@isabelle.db.elephantsql.com/gzxgfccf")#
eng_sqlite = create_engine("sqlite:///pokemon.bd")

con_sqlite = eng_sqlite.connect()
con_postgres = eng_postgres.connect()

eng_sqlite_novo = create_engine("sqlite:///pokemon_novo.bd")
con_sqlite_novo = eng_sqlite_novo.connect()

query = text("""
CREATE TABLE treinadores(
  id SERIAL PRIMARY KEY,
  nome VARCHAR(15),
  cidade VARCHAR(15),
  insignias SMALLINT
);
""")

query.text

con_sqlite_novo.execute(query)

treinadores = [
    {
        'nome': 'Ash',
        'cidade': 'Pallet',
        'insignias': 0
    },
    {
        'nome': 'Feulo',
        'cidade': 'SP',
        'insignias': 5
    },
    {
        'nome': 'Brock',
        'cidade': 'Pewter',
        'insignias': 2
    }
  ]

for treinador in treinadores:
  con_sqlite_novo.execute(text(f"INSERT INTO Treinadores(nome, cidade, insignias) VALUES ('{treinador['nome']}', '{treinador['cidade']}', '{treinador['insignias']}')"))

con_sqlite_novo.commit()

rs = con_sqlite_novo.execute(text("SELECT * FROM Treinadores;"))

for result in rs.fetchall():
  print(result)

con_sqlite.close()
con_postgres.close()
con_sqlite_novo.close()

# abre uma conexão com o banco e executa código SQL
with eng_sqlite_novo.connect() as con:
  con.execute(text("""CREATE TABLE Pokemon(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome VARCHAR(15),
  tipo VARCHAR(15),
  nivel SMALLINT,
  capturado_em TIMESTAMPTZ,
  id_treinador INTEGER NOT NULL REFERENCES Treinadores(id)
);"""))

with eng_sqlite.connect() as con:
  con.execute(text("DROP TABLE pokemon;"))
  con.commit()





data = [
    {'nome': 'Ash', 'cidade': 'Pallet', 'insignias': 2},
    {'nome': 'Feulo','cidade': 'SP','insignias': 4},
    {'nome': 'Brock','cidade': 'Pewter', 'insignias': 1}
]
# Inserindo dados
#with eng_postgres.connect() as con:
with eng_sqlite.connect() as con:
  for line in data:
    con.execute(text(f"INSERT INTO treinadores(nome, cidade, insignias) VALUES('{line['nome']}', '{line['cidade']}', {line['insignias']})"))
  con.commit()

# Recebendo dados
with eng_sqlite.connect() as con:
  rs = con.execute(text("SELECT * FROM treinadores"))
  print(rs.fetchall())

"""### SQL Expression Language

#### Definição de Schemas
"""

from sqlalchemy import Table, Column, Integer, String, MetaData

# Cria um ojeto de metadata. Metadatas são coleçoes de tabelas e sua infos
meta = MetaData()

eng_sqlite_3 = create_engine("sqlite:///pokemon_3.bd")
con_sqlite_3 = eng_sqlite_3.connect()

#Cria um objeto do tipo tabela que abstrai uma tabela no Banco de dados
treinadores = Table('treinadores', meta,
     Column('id', Integer, primary_key=True, autoincrement=True, nullable=False),
     Column('nome', String(25), unique=True, nullable=False),
     Column('cidade', String(25)),
     Column('insignias', Integer, default=0),
     extend_existing=True
)

print("The Name column:")
print(treinadores.columns.nome)
print(treinadores.c.nome)

print("Columns: ")
for col in treinadores.c:
    print(col)

print("Primary keys:")
for pk in treinadores.primary_key:
    print(pk)

print("The id column:")
print(treinadores.c.id.name)
print(treinadores.c.id.type)
print(treinadores.c.id.nullable)
print(treinadores.c.id.primary_key)

for table in meta.tables:
    print(table)

meta.reflect(bind=eng_sqlite_3)
for table in meta.tables:
    print(table)

meta.create_all(bind=eng_sqlite_3)

from sqlalchemy import inspect

insp = inspect(eng_postgres)
print(insp.get_table_names())
print(insp.get_columns("treinadores"))
print(insp.get_pk_constraint("treinadores"))

meta.create_all(eng_postgres)

"""##### Expression Language (DML)"""

from sqlalchemy.sql import select

with eng_sqlite.connect() as con:
  stm = select(treinadores.c.nome, treinadores.c.insignias, treinadores.c.cidade)
  rs = con.execute(stm)
  print(rs.fetchall())

# LIMIT
with eng_sqlite.connect() as con:
  stm = select(treinadores.c.nome, treinadores.c.insignias).limit(1)
  rs = con.execute(stm)
  print(rs.fetchall())

from sqlalchemy.sql import and_, or_

# WHERE
with eng_sqlite.connect() as con:
  stm = select(treinadores).where(and_(treinadores.c.insignias > 1, treinadores.c.cidade == "Pallet"))
  rs = con.execute(stm)
  print(rs.fetchall())

print(stm)

#LIKE
with eng_postgres.connect() as con:
  stm = select(treinadores).where(treinadores.c.nome.like('G%'))
  rs = con.execute(stm)
  print(rs.fetchall())

from sqlalchemy.sql import asc, desc

# Order By
with eng_sqlite.connect() as con:
  s = select(treinadores.c['nome', 'insignias']).order_by(desc(treinadores.c.insignias))
  rs = con.execute(s)
  for result in rs.fetchall():
    print(result[0], result[1])

#AUTOLOAD
pokemon = Table('Pokemon', meta, autoload=True)

with eng.connect() as con:
  stm = pokemon.insert().values([
      {
          'nome': 'Pikachu',
          'nivel': 10,
          'codigo_treinador': 1
      },
       {
          'nome': 'Charmander',
          'nivel': 3,
          'codigo_treinador': 2
      }
  ])
  con.execute(stm)
  con.commit()

with eng.connect() as con:
  stm = select(pokemon.c['nome', 'nivel'], treinadores.c['nome', 'cidade']).join(treinadores)
  rs = con.execute(stm)
  print(rs.fetchall())

pokecenters = Table('pokecenters', meta,
  Column('codigo', Integer, primary_key=True),
  Column('cidade', String(25), nullable=False)
)

"""### Object-Relational Mapping (ORM)"""

from sqlalchemy.orm import declarative_base, Session
from sqlalchemy.exc import IntegrityError

# Classes Bases e Sessão
meta_orm = MetaData()
Base = declarative_base(metadata=meta_orm)

class Treinador(Base):
  __tablename__ = "treinadores"
  id = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
  nome = Column(String(25), nullable=False, unique=True)
  cidade = Column(String(25))
  insignias = Column(Integer, default=0)

  def __repr__(self):
    return f"<Treinador({self.nome})>"

  def ganhar_insignia(self):
    self.insignias +=1

Base.metadata.reflect(eng_postgres)

Base.metadata.create_all(bind=eng_postgres)

t1 = Treinador(nome='Ash', cidade='Pallet')
t2 = Treinador(nome='Gary', cidade='Pallet')
t3 = Treinador(nome='Feulo', cidade='SP')

with Session(eng_postgres) as s:
  s.add_all([t1, t2, t3])
  s.commit()

#SELECT
#Session = sessionmaker(metadata=meta_orm)
with Session(eng_postgres) as s:
  rs = s.query(Treinador).order_by(Treinador.nome).all()
  treinadores = list(rs)
  #ash = treinadores[0]
  #print(ash.pokemon)
print(treinadores)

ash = treinadores[0]

ash.cidade

ash.ganhar_insignia()

ash.insignias

with Session(eng_postgres) as s:
  s.add(ash)
  s.commit()

### CRIANDO UM NOVO TREINADOR
ash2 = Treinador(nome="Ash", cidade="Pallet", insignias=1)

print(ash, ash2)

with Session(eng_postgres) as s:
  try:
    s.add(ash2)
    s.commit()
  except IntegrityError:
    print("Ja existe um treinador com esse nome")
    s.rollback()

from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship

class Pokemon(Base):
  __tablename__ = "pokemon"
  extend_existing= True
  id = Column(Integer, primary_key=True, autoincrement=True)
  nome = Column(String(10), nullable=False)
  tipo = Column(String(25))
  nivel = Column(Integer, default=1)
  id_treinador = Column(Integer, ForeignKey("treinadores.id"), nullable=False)
  treinador = relationship(Treinador, backref="pokemon")

  def __repr__(self):
    return f"<Pokemon({self.nome},{self.nivel})>"

  def subir_de_nivel(self):
    self.nivel +=1

Base.metadata.create_all(bind=eng_postgres)

pokemon = [
    Pokemon(nome="Pikachu", tipo="Elétrico", nivel=5, treinador=ash),
    Pokemon(nome="Mewtwo", tipo="Psiquico", nivel=99, treinador=treinadores[1]),
    ]
with Session(eng_postgres) as s:
  try:
    s.add_all(pokemon)
    s.commit()
  except IntegrityError:
    print("Ja existe um treinador com esse codigo")
    s.rollback()

with Session(eng_postgres) as s:
  rs = s.query(Treinador).order_by(Treinador.nome).all()
  treinadores[0]
  #ash = treinadores[0]
  #print(ash.pokemon)

treinadores[0].pokemon









from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship

class Ginasio(Base):
  __tablename__ = "ginasios"
  codigo = Column(Integer, primary_key=True, autoincrement=True)
  nome = Column(String(25))
  cidade = Column(String(25))
  codigo_lider = Column(Integer, ForeignKey("treinadores.codigo"),nullable=False)
  lider = relationship("Treinadores", backref="ginasio")
  def __repr__(self):
    return f"<Ginasio({self.nome})>"

Base.metadata.create_all(bind=eng_postgres)

with Session(eng) as s:
  try:
    rs = s.query(Treinador).all()
    brock = list(rs)[2]
    #ginasio_pewter = Ginasio(nome="Ginasio Pewter", lider=brock)
    #s.add(ginasio_pewter)
    #s.commit()
  except IntegrityError:
    #print("Ja existe um treinador com esse codigo")
    #s.rollback()
    pass

try:
  with Session() as s:
    s.add_all([
      Carro(nome='Mercedes', preco=57127),
      Carro(nome='Skoda', preco=9000),
      Carro(nome='Volvo', preco=29000),
      Carro(nome='Bentley', preco=350000),
      Carro(nome='Citroen', preco=21000),
      Carro(nome='Hummer', preco=41400),
      Carro(nome='Volkswagen', preco=21600)
    ])
    s.commit()
except Exception as e:
  print("Deu ruim!")

from sqlalchemy.sql import func

with Session() as s:
  carros_caros = s.query(func.avg(Carro.preco)).filter(Carro.preco>25000).all()

carros_caros

carros_caros[4].preco

mercedez = carros_caros[1]

mercedez.preco

with Session() as s:
 hummer = s.query(Carro).filter(Carro.nome=="Hummer").first()

if hummer:
  print(hummer.nome)
else:
  print("Nome não existente")

with Session() as ses:
  try:
    ses.delete(hummer)
    ses.commit()
  except IntegrityError:
    print("Ja existe um carro com esse nome")
    ses.rollback*()



Base = declarative_base(bind=eng_postgres)

class Author(Base):
  __tablename__ = "Authors"

  author_id = Column('author_id', Integer, primary_key=True, autoincrement=True)
  name = Column(String)

  def __init__(self, name):
    self.name = name

  def __repr__(self):
    return f"<Author: {self.name}>"

class Book(Base):
  __tablename__ = "Books"

  book_id = Column(Integer, primary_key=True, autoincrement=True)
  title = Column(String)
  author_id = Column(Integer, ForeignKey("Authors.author_id"),nullable=False,)
  author = relationship("Author", backref="books")

  def __init__(self, title):
    self.title = title


  def __repr__(self):
    return f"<Book: {self.title} - {self.author.name}>"

Base.metadata.create_all()

jane =  Author('Jane Austen')
leo = Author('Leo Tolstoy')
heller =  Author('Joseph Heller')
dickens = Author('Charles Dickens')

ses.rollback()

jane = ses.query(Author).filter(Author.name == "Jane Austen").first()
leo= ses.query(Author).filter(Author.name == "Leo Tolstoy").first()
heller = ses.query(Author).filter(Author.name == "Joseph Heller").first()
dickens = ses.query(Author).filter(Author.name == "Charles Dickens").first()





jane.books.append(Book('Emma'))

leo.books.append(Book('War and Peace'))
heller.books.append(Book('Catch XII'))
leo.books.append(Book('Good as Gold'))
jane.books.append(Book('Anna Karenia'))
dickens.books.append(Book('David Copperfield'))

ses.add_all([leo, heller, jane, dickens])
ses.commit()

with Session() as s:
  res = s.query(Author).all()
  print(res)

with Session() as s:
  res = s.query(Book).all()
  print(res)

with Session() as s:
  res = s.query(Author).filter(Author.name=="Leo Tolstoy").first()
  print(res.name)
  for book in res.books:
    print (book.title)

ses.close()

with Session() as s:
  res = s.query(Author).filter(Author.books.any(title="Good as Gold")).first()
  print(res.name)

with eng_postgres.connect() as con:
  rs = con.execute(text("SELECT * FROM Books"))
  print(rs.fetchall())

insp.get_table_names()

insp.get_schema_names()

ses.query(Book).all()

with Session() as s:
  s.query(Book).all()

ses.commit()

ses.is_active